import Head from 'next/head'
import Image from 'next/image'
import {server} from '../config'
import { Inter } from '@next/font/google'
import Card from '../components/Card'
import Collection from '../components/Collection'

const inter = Inter({ subsets: ['latin'] })

export default function Home({cardData, collectionData}) {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="dashboard">
            <div className="left-dash" style={{position:"relative"}}>
                <div className="dash-title">
                    <h1 className ="welcome-text">Welcome to SolBuzz</h1> 
                </div>
                <h3>Explore</h3>
                <div className="dash-cards">
                    {cardData.map((item, index) => (
                        <Card 
                            key={index}
                            cardImage={item.cardImage}
                            bottomText1={item.bottomText}
                            peopleImage1={item.peopleImage1}
                            peopleImage2={item.peopleImage2}
                            peopleImage3={item.peopleImage3}
                            peopleImage4={item.peopleImage4}
                            peopleImage5={item.peopleImage5}
                        />
                    ))}
                </div>
            </div>
            <div className="right-dash">
                <div className="collection">
                    <h3 className='col-title'>Top Categries</h3>
                    <div className="col-cards">
                        {collectionData.map((item, index) => (
                            <Collection 
                                key = {index}
                                cNumber = {item.cNumber}
                                cImage = {item.cImage}
                                cTitle = {item.cTitle}
                                cMail = {item.cMail}
                            />
                        ))}
                    </div>
                </div>
                <div className="activity">
                        <h3>Recent Activity</h3>
                </div>
            </div>
        </div>
    </>
  )
}

export const getStaticProps = async() => {
  // const res = await fetch('https://jsonplaceholder.typicode.com/posts?_limit=3')
  const resCard = await fetch(`${server}/api/cardData`)
  const resCollection = await fetch(`${server}/api/collectionData`)

  const {cardData} = await resCard.json()
  const {collectionData} = await resCollection.json()
  // will receive `posts` as a prop at build time
  return {
    props: {
      cardData,
      collectionData
    },
  }
}